spring:
  datasource:
    url: jdbc:h2:file:./data/gaia_space_dev;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: 
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

logging:
  level:
    com.gaiaspace: DEBUG
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG